apiVersion: core.portra.run/v1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: portra-operator
    app.kubernetes.io/managed-by: kustomize
  name: app-sample
spec:
  image: "nginx:latest"
  containerPort: 80
  replicas: 2
  domains:
    - "nginx.portra.local"
  tls: false
  env:
    - name: "PORTRA_ENV"
      value: "production"
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
